# Generated by Django 3.1.2 on 2020-10-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='courseVideosRES'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(default='', upload_to='courseVideos', verbose_name='videos de curso'),
            preserve_default=False,
        ),
    ]
