# Generated by Django 3.1.2 on 2020-10-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.order')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_estado', models.CharField(max_length=100)),
                ('total_de_la_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('correo_cliente', models.EmailField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=100)),
                ('cursos', models.ManyToManyField(related_name='comprado', to='shopping_cart.Order')),
            ],
            options={
                'verbose_name': 'Facturacion',
                'verbose_name_plural': 'Facturaciones',
            },
        ),
    ]
