# Generated by Django 3.1.2 on 2020-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
