# Generated by Django 3.1.2 on 2020-10-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
        ('paypal', '0002_compra_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='order',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total_amount',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.order')),
            ],
        ),
    ]
