# Generated by Django 3.1.2 on 2020-10-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('paypal', '0003_auto_20201021_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Facturacion', 'verbose_name_plural': 'Facturaciones'},
        ),
        migrations.AddField(
            model_name='compra',
            name='cursos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.course'),
        ),
    ]
