# Generated by Django 3.1.2 on 2020-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('paypal', '0004_auto_20201022_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cursos',
        ),
        migrations.AddField(
            model_name='compra',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, to='content.Course'),
        ),
    ]
