# Generated by Django 3.1.2 on 2020-10-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0006_compra_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='productos',
        ),
    ]
