# Generated by Django 3.1.2 on 2020-10-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('paypal', '0007_auto_20201022_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='content.Course'),
        ),
    ]
