# Generated by Django 3.1.2 on 2020-10-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_course_author'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='content.Course'),
        ),
    ]
