# Generated by Django 3.1.2 on 2020-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product',
            field=models.ManyToManyField(blank=True, to='content.Product'),
        ),
    ]
